halyard:
  # If spinnakerVersion is not specified appVersion in Chart.yml is chosen for Spinnaker
  spinnakerVersion: 1.26.7
  image:
    repository: us-docker.pkg.dev/spinnaker-community/docker/halyard
    tag: 1.39.0
    pullSecrets: []
  # Set to false to disable persistence data volume for halyard
  persistence:
    enabled: true
  # Uncomment to add storage class for the persistence data volume
  # storageClass: <storageclass_name>
  # Provide additional parameters to halyard deploy apply command
  additionalInstallParameters: []
  # Provide a config map with Hal commands that will be run the core config (storage)
  # The config map should contain a script in the config.sh key
  additionalScripts:
    enabled: false
    configMapName: my-halyard-config
    configMapKey: config.sh
    # If you'd rather do an inline script, set create to true and put the content in the data dict like you would a configmap
    # The content will be passed through `tpl`, so value interpolation is supported.
    create: false
    data: {}
  additionalSecrets:
    create: false
    data: {}
    ## Uncomment if you want to use a pre-created secret rather than feeding data in via helm.
    # name:
  additionalConfigMaps:
    create: false
    data: {}
    ## Uncomment if you want to use a pre-created ConfigMap rather than feeding data in via helm.
    # name:
  ## Define custom profiles for Spinnaker services. Read more for details:
  ## https://www.spinnaker.io/reference/halyard/custom/#custom-profiles
  ## The contents of the files will be passed through `tpl`, so value interpolation is supported.
  additionalProfileConfigMaps:
    data: {}
      ## if you're running spinnaker behind a reverse proxy such as a GCE ingress
      ## you may need the following profile settings for the gate profile.
      ## see https://github.com/spinnaker/spinnaker/issues/1630
      ## otherwise its harmless and will likely become default behavior in the future
      ## According to the linked github issue.
      # gate-local.yml:
      #   server:
      #     tomcat:
      #       protocolHeader: X-Forwarded-Proto
      #       remoteIpHeader: X-Forwarded-For
      #       internalProxies: .*
      #       httpsServerPort: X-Forwarded-Port

  ## Define custom settings for Spinnaker services. Read more for details:
  ## https://www.spinnaker.io/reference/halyard/custom/#custom-service-settings
  ## You can use it to add annotations for pods, override the image, etc.
  additionalServiceSettings:
    # deck.yml:
    #   artifactId: gcr.io/spinnaker-marketplace/deck:2.9.0-20190412012808
    #   kubernetes:
    #     podAnnotations:
    #       iam.amazonaws.com/role: <role_arn>
    clouddriver.yml:
      kubernetes:
        nodeSelector:
          node: spinnaker-poc
        deploymentEnvironment:
          nodeSelector:
            node: spinnaker-poc
    deck.yml:
      kubernetes:
        nodeSelector:
          node: spinnaker-poc
        deploymentEnvironment:
          nodeSelector:
            node: spinnaker-poc 
    echo.yml:
      kubernetes:
        nodeSelector:
          node: spinnaker-poc
        deploymentEnvironment:
          nodeSelector:
            node: spinnaker-poc
    front50.yml:
      kubernetes:
        nodeSelector:
          node: spinnaker-poc
        deploymentEnvironment:
          nodeSelector:
            node: spinnaker-poc
    gate.yml:
      kubernetes:
        nodeSelector:
          node: spinnaker-poc
        deploymentEnvironment:
          nodeSelector:
            node: spinnaker-poc
    igor.yml:
      kubernetes:
        nodeSelector:
          node: spinnaker-poc
        deploymentEnvironment:
          nodeSelector:
            node: spinnaker-poc
    orca.yml:
      kubernetes:
        nodeSelector:
          node: spinnaker-poc
        deploymentEnvironment:
          nodeSelector:
            node: spinnaker-poc
    rosco.yml:
      kubernetes:
        nodeSelector:
          node: spinnaker-poc
        deploymentEnvironment:
          nodeSelector:
            node: spinnaker-poc

  ## Populate to provide a custom local BOM for Halyard to use for deployment. Read more for details:
  ## https://www.spinnaker.io/guides/operator/custom-boms/#boms-and-configuration-on-your-filesystem
  bom: ~ #|-
  #   artifactSources:
  #     debianRepository: https://dl.bintray.com/spinnaker-releases/debians
  #     dockerRegistry: gcr.io/spinnaker-marketplace
  #     gitPrefix: https://github.com/spinnaker
  #     googleImageProject: marketplace-spinnaker-release
  #   dependencies:
  #     consul:
  #       version: 0.7.5
  #     redis:
  #       version: 2:2.8.4-2
  #     vault:
  #       version: 0.7.0
  #   services:
  #     clouddriver:
  #       commit: 031bcec52d6c3eb447095df4251b9d7516ed74f5
  #       version: 7.3.3-20210322155326
  #     deck:
  #       commit: b0aac478e13a7f9642d4d39479f649dd2ef52a5a
  #       version: 3.6.1-20210329201325
  #     defaultArtifact: {}
  #     echo:
  #       commit: 7aae2141883240bd5747b981b2196adfa5b24225
  #       version: 2.16.0-20210208200018
  #     fiat:
  #       commit: e92cfbcac018d9dcfa03869224f7106bf2a11315
  #       version: 1.7.0-20190904130744
  #     front50:
  #       commit: abc5c168e3619ac084d4130eef7313cbdcfc3f61
  #       version: 0.26.2-20210216140019
  #     gate:
  #       commit: fd0128a6b79ddaca984c3bcdd1259c14f167cd2d
  #       version: 1.21.0-20210215200018
  #     igor:
  #       commit: c9bbca8e5c340d90b812f4fd27c6ebe3088dbc8d
  #       version: 1.15.0-20210208200018
  #     kayenta:
  #       commit: 8aa41e6e723e8d37831f5d4fe0bd5aa24ede5872
  #       version: 0.11.0-20190830172818
  #     monitoring-daemon:
  #       commit: 922385def92058877d61dfc835873539f0377cd7
  #       version: 0.15.0-20190820135930
  #     monitoring-third-party:
  #       commit: 922385def92058877d61dfc835873539f0377cd7
  #       version: 0.15.0-20190820135930
  #     orca:
  #       commit: 7b4e3dd6c4393ba88ebb3ea209a9c95df63e5e87
  #       version: 2.19.0-20210209140018
  #     rosco:
  #       commit: cfb88bb57f7af064876cfe5eef3c330a2621507b
  #       version: 0.14.0-20190904130744
  #   timestamp: '2019-09-16 18:18:44'
  #   version: 1.26.7

  ## Define local configuration for Spinnaker services.
  ## The contents of these files would be copies of the configuration normally retrieved from
  ## `gs://halconfig/<service-name>`, but instead need to be available locally on the halyard pod to facilitate
  ## offline installation. This would typically be used along with a custom `bom:` with the `local:` prefix on a
  ## service version.
  ## Read more for details:
  ## https://www.spinnaker.io/guides/operator/custom-boms/#boms-and-configuration-on-your-filesystem
  ## The key for each entry must be the name of the service and a file name separated by the '_' character.
  serviceConfigs: {}
  # clouddriver_clouddriver-ro.yml: |-
  #   ...
  # clouddriver_clouddriver-rw.yml: |-
  #   ...
  # clouddriver_clouddriver.yml: |-
  #   ...
  # deck_settings.json: |-
  #   ...
  # echo_echo.yml: |-
  #   ...

  ## Uncomment if you want to add extra commands to the init script
  ## run by the init container before halyard is started.
  ## The content will be passed through `tpl`, so value interpolation is supported.
  # additionalInitScript: |-

  ## Uncomment if you want to add annotations on halyard and install-using-hal pods
  # annotations:
  #   iam.amazonaws.com/role: <role_arn>

  ## Uncomment the following resources definitions to control the cpu and memory
  # resources allocated for the halyard pod
  resources: {}
    # requests:
    #   memory: "1Gi"
    #   cpu: "100m"
    # limits:
    #   memory: "2Gi"
    #   cpu: "200m"

  ## Uncomment if you want to set environment variables on the Halyard pod.
  # env:
  #   - name: JAVA_OPTS
  #     value: -Dhttp.proxyHost=proxy.example.com
  customCerts:
    ## Enable to override the default cacerts with your own one
    enabled: false
    secretName: custom-cacerts

# Define which registries and repositories you want available in your
# Spinnaker pipeline definitions
# For more info visit:
#   https://www.spinnaker.io/setup/providers/docker-registry/

# Configure your Docker registries here
dockerRegistries:
- name: dockerhub
  address: index.docker.io
  repositories:
    - library/alpine
    - library/ubuntu
    - library/centos
    - library/nginx
# - name: gcr
#   address: https://gcr.io
#   username: _json_key
#   password: '<INSERT YOUR SERVICE ACCOUNT JSON HERE>'
#   email: 1234@5678.com
# - name: ecr
#   address: <AWS-ACCOUNT-ID>.dkr.ecr.<REGION>.amazonaws.com
#   username: AWS
#   passwordCommand: aws --region <REGION> ecr get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d | sed 's/^AWS://'

# If you don't want to put your passwords into a values file
# you can use a pre-created secret instead of putting passwords
# (specify secret name in below `dockerRegistryAccountSecret`)
# per account above with data in the format:
# <name>: <password>

# dockerRegistryAccountSecret: myregistry-secrets

kubeConfig:
  # Use this when you want to register arbitrary clusters with Spinnaker
  # Upload your ~/kube/.config to a secret
  enabled: true
  secretName: my-kubeconfig
  secretKey: kube-config
  # Use this when you want to configure halyard to reference a kubeconfig from s3
  # This allows you to keep your kubeconfig in an encrypted s3 bucket
  # For more info visit:
  #   https://www.spinnaker.io/reference/halyard/secrets/s3-secrets/#secrets-in-s3
  # encryptedKubeconfig: encrypted:s3!r:us-west-2!b:mybucket!f:mykubeconfig
  # List of contexts from the kubeconfig to make available to Spinnaker
  contexts:
  - spinnaker
  deploymentContext: spinnaker
  # Use this to limit the namespaces this kubernetes account will access.
  # Note, if you use nameSpaces, omittedNameSpaces will not be used.
  # Note, the casing of the nameSpace variable here.
  # nameSpaces:
  # - namespace1
  # - namespace2
  omittedNameSpaces:
  - kube-system
  - kube-public
  onlySpinnakerManaged:
    enabled: false

  # When false, clouddriver will skip the permission checks for all kubernetes kinds at startup.
  # This can save a great deal of time during clouddriver startup when you have many kubernetes
  # accounts configured. This disables the log messages at startup about missing permissions.
  checkPermissionsOnStartup: true

  # A list of resource kinds this Spinnaker account can deploy to and will cache.
  # When no kinds are configured, this defaults to ‘all kinds'.
  # kinds:
  # -

  # A list of resource kinds this Spinnaker account cannot deploy to or cache.
  # This can only be set when –kinds is empty or not set.
  # omittedKinds:
  # -

  # When true, clouddriver will query manifest status during pipeline executions using live
  # data rather than the cache. This eliminates all time spent in the “force cache refresh”
  # task in pipelines, greatly reducing execution time.
  liveManifestCalls: false

# Change this if youd like to expose Spinnaker outside the cluster
ingress:
  enabled: true
  host: spinnaker-helm.jerr.uk
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-headers: '*'
    nginx.ingress.kubernetes.io/cors-allow-methods: '*'
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/32
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: spinnaker-auth
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - Spinnaker'
  tls: []

ingressGate:
  enabled: false
  # host: gate.spinnaker.example.org
  # annotations:
    # ingress.kubernetes.io/ssl-redirect: 'true'
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # tls:
  #  - secretName: -tls
  #    hosts:
  #      - domain.com

# spinnakerFeatureFlags is a list of Spinnaker feature flags to enable
# Ref: https://www.spinnaker.io/reference/halyard/commands/#hal-config-features-edit
spinnakerFeatureFlags:
  - artifacts
#   - pipeline-templates
# spinnakerFeatureFlags:
# - artifacts:
#   github:
#     enabled: true
#     accounts:
#     - name: e20c15fb43dbf570bfaa
#       token: e1c47a6e71d0e8ab8cafcc123bf967031efce259


# Node labels for pod assignment
# Ref: https://kubernetes.io/docs/user-guide/node-selection/
# nodeSelector to provide to each of the Spinnaker components
nodeSelector:
  node: spinnaker-poc

# Node tolerations
# Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
tolerations: []

# Redis password to use for the in-cluster redis service
# Enable redis to use in-cluster redis
redis:
  enabled: true
  # External Redis option will be enabled if in-cluster redis is disabled
  external:
    host: "<EXTERNAL-REDIS-HOST-NAME>"
    port: 6379
    # password: ""
  password: #password
  nodeSelector: {}
  cluster:
    enabled: false
# Uncomment if you don't want to create a PVC for redis
#  master:
#    persistence:
#      enabled: false

gcs:
  enabled: false
  project: my-project-name
  bucket: "<GCS-BUCKET-NAME>"
  ## if jsonKey is set, will create a secret containing it
  jsonKey: '<INSERT CLOUD STORAGE JSON HERE>'
  ## override the name of the secret to use for jsonKey, if `jsonKey`
  ## is empty, it will not create a secret assuming you are creating one
  ## external to the chart. the key for that secret should be `key.json`.
  secretName:

# AWS Simple Storage Service
s3:
  enabled: true
  bucket: #bucket # Change to a unique name. Spinnaker stores application and pipeline definitions here
  rootFolder: #rootfolder
  region: #region
  accessKey: #accesskey
  secretKey: #secretkey
  extraArgs: []
  #  - "--path-style-access true"
github:
  enabled: true
  accountName: #account
  accountToken: #token

# Azure Storage Account
azs:
  enabled: false
#   storageAccountName: ""
#   accessKey: ""
#   containerName: "spinnaker"

rbac:
  # Specifies whether RBAC resources should be created
  create: true
  # Specifies whether PSP resources should be created
  pspEnabled: false

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccounts to use.
  # If left blank it is auto-generated from the fullname of the release
  halyardName:
  spinnakerName:
  serviceAccountAnnotations: {}
securityContext:
  # Specifies permissions to write for user/group
  runAsUser: 1000
  fsGroup: 1000
