{{- if and .Values.github.enabled .Values.github.accountName .Values.github.accountToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "spinnaker.fullname" . }}-github
  labels:
{{ include "spinnaker.standard-labels" . | indent 4 }}
    component: halyard
type: Opaque
data:
  accountName: {{ .Values.github.accountName | b64enc | quote }}
  accountToken: {{ .Values.github.accountToken | b64enc | quote }}
{{- end }}
